version: "2"

services:
  webapp:
    build: .
    volumes:
      - ./instance:/app/instance
    environment:
      VIRTUAL_HOST: mealplan.craigattwood.co.uk
      LETSENCRYPT_HOST: mealplan.craigattwood.co.uk
    network_mode: bridge
